name: react-native-android-build-apk
on:
  push:
    branches:
      - master
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install npm dependencies
        run: |
          cd Bindr && npm install
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install npm dependencies
        run: |
          cd Bindr && npm install
      - name: Build Android Release
        run: |
          cd Bindr && cd android && chmod +x ./gradlew && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: Bindr-Release.apk
          path: Bindr/android/app/build/outputs/apk/release/
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "Bindr/android/app/build/outputs/apk/release/Bindr-Release.apk"
          token: ${{ secrets.GITHUB_TOKEN }}